return PlaceObj('ModDef', {
	'title', "Antonov",
	'description', 'Second entry in the "Echoes of a Cold War" series of custom mercs for Jagged Alliance 3 is a less known character from the franchise Call of Duty: Black Ops Cold War. Featuring in multiplayer as an Operator for the Warsaw Pact: Maxim Antonov.\n\nThe aim of the mod was to bring high-quality seamless integration with the game. Hopefully this mod will feel like an official crossover.\n\n- Own model ported from Cold War, optimazed for the game engine and artistic style.\n- 230 voice responses ported from Cold War, made fit for all in-game scenarios (English only).\n- Custom render of the character portrait made to fit the game style.\n- Custom perk Guardian is desigened to boost your squad\'s toughness as the battle progresses.\n\nCharacter, model, and voice acting are properties of Activision and Treyarch. All rights belong to them.\nCredits: Soundwave2142 - Port of the character and mod set up.',
	'image', "Mod/trKkXGq/Images/preview.png",
	'external_links', {
		"https://steamcommunity.com/sharedfiles/filedetails/?id=3448840884",
		"https://github.com/Soundwave2142/ja3-merc-antonov",
	},
	'last_changes', "Initial Mod upload",
	'id', "trKkXGq",
	'author', "Soundwave2142",
	'version_major', 1,
	'version', 347,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'entities', {
		"Hat_Antnv",
		"Head_Antnv",
		"Armor_Antnv",
		"Shirt_Antnv",
		"Pants_Antnv",
	},
	'code', {
		"UnitData/Antonov.lua",
		"CharacterEffect/AntonovEffect.lua",
		"CharacterEffect/Granite.lua",
		"Code/Misc.lua",
		"Entities/Hat_Antnv.lua",
		"Entities/Head_Antnv.lua",
		"Entities/Armor_Antnv.lua",
		"Entities/Shirt_Antnv.lua",
		"Entities/Pants_Antnv.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1743700945,
	'code_hash', 7186453273738850960,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Antonov",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "AntonovEffect",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Granite",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Antonov",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Antonov",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "VoiceResponse",
			'Id', "Antonov",
			'ClassDisplayName', "Unit voice responses",
		}),
	},
	'steam_id', "3448840884",
	'TagMercs', true,
})